FROM python:3.12-slim AS builder

WORKDIR /install

COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

# ---

FROM python:3.12-slim AS runtime

WORKDIR /app

COPY --from=builder /root/.local /usr/local
COPY app.py .

EXPOSE 5001

CMD ["python", "app.py"]


