server {
    listen 80;
    listen [::]:80;

    server_name personal-info.local;

    root /var/www/server1;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /var/log/nginx/personal-profile.access.log;
    error_log /var/log/nginx/personal-profile.error.log;
}
