server {
    listen 80;
    listen [::]:80;

    server_name grp1-frontend.heinux-training.org;

    root /var/www/frontend;
    index index.html;

    access_log /var/log/nginx/react-frontend.access.log;
    error_log /var/log/nginx/react-frontend.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}
